spring.application.name=book-client-spring
spring.main.web-application-type=NONE
service.host=localhost
service.port=8081
service.api=api/citizens
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
